In [20]:
#Question1
import numpy as np
x=np.array([1,2,4,5])
print(x)
y=x.tolist()
print("si x était une liste elle sera : ",y)

[1 2 4 5]
si x était une liste elle sera :  [1, 2, 4, 5]


In [31]:
#Question2
import numpy as np
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
b=a.trace()
print("the sum of the diagonal elements of a : ",b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
the sum of the diagonal elements of a :  15


In [61]:
#Question3
import numpy as np
h=np.array([1,2,3,4,5,6,7,8,9])
print(h)
x=input()
x=int(x)
for i in h:
    if i > x:
        print(i)


[1 2 3 4 5 6 7 8 9]
5
6
7
8
9


In [77]:
#Question4
import numpy as np
g=np.array([[1,3],[5,7]])
e=np.array([[2,4],[6,8]])
a=np.array([1,2,3])
b=np.array([5,7,13])
print(g+e)
print(a+b)

[[ 3  7]
 [11 15]]
[ 6  9 16]


In [85]:
#Question5
import numpy as np
v=np.array([(1,2,3),(4,5,6)])
print(v[0,:].mean())
print(v[1,:].mean())

2.0
5.0
